# Generated by Django 3.1.2 on 2020-12-09 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iata', models.CharField(max_length=5)),
                ('icao', models.CharField(max_length=5)),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('gps', models.CharField(max_length=200)),
            ],
        ),
    ]
